### ISSUE TITLE
Не запускается(

### ISSUE THREAD

**Issue by nikon-ru** [AVStreamAI/avstream_rtmp_monitoring_recording_restreaming_tg#1]
Приветствую!
Во время запуска скрипта в обычном режиме выдает следующее:
RTMP Monitor Startup Script
========================

Installing dependencies...
npm ERR! code EPERM
npm ERR! syscall mkdir
npm ERR! path C:\Program Files (x86)\AVStream Strimometr 0.5.2\node_modules
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, mkdir 'C:\Program Files (x86)\AVStream Strimometr 0.5.2\node_modules'
npm ERR!  [Error: EPERM: operation not permitted, mkdir 'C:\Program Files (x86)\AVStream Strimometr 0.5.2\node_modules'] {
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: 'C:\\Program Files (x86)\\AVStream Strimometr 0.5.2\\node_modules'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in: C:\Users\Tablo\AppData\Local\npm-cache\_logs\2024-12-05T08_50_39_851Z-debug-0.log
Failed to install dependencies
Press any key to exit...

При запуске от имени администратора ошибок поменьше) И все, далее ничего не происходит. Куда копать?

**Comment by AVStreamAI** [comment]
Ошибка **EPERM** (`operation not permitted`) при установке зависимостей через `npm` обычно связана с проблемами прав доступа. Конкретно в вашем случае `npm` не может создать папку `node_modules` в каталоге `C:\Program Files (x86)\AVStream Strimometr 0.5.2`, поскольку этот каталог, как и большинство системных папок, защищён от изменений без прав администратора.

### Возможные причины и решения:

#### 1. **Отсутствие прав администратора**
   - Установка зависимостей в системных каталогах требует прав администратора.
   - Запустите консоль (например, PowerShell или CMD) от имени администратора:
     1. Найдите ярлык консоли, например, "Командная строка" или "PowerShell".
     2. Кликните правой кнопкой мыши → "Запуск от имени администратора".
     3. Выполните команду снова.

#### 2. **Переместите проект в директорию с обычными правами**
   - Избегайте размещения проекта в системных папках вроде `C:\Program Files (x86)`.
   - Переместите проект в директорию, к которой у вас есть полный доступ, например:
     ```
     C:\Users\<Ваш пользователь>\Documents\AVStream Strimometr
     ```
   - После перемещения повторите установку зависимостей:
     ```bash
     npm install
     ```

#### 3. **Проблемы с антивирусом**
   - Антивирус или другая система защиты может блокировать создание новых файлов и папок.
   - Временно отключите антивирус или добавьте исключение для вашего проекта.

#### 4. **Конфликт с другими процессами**
   - Если файлы или папки проекта открыты в других приложениях (например, в редакторе), это может блокировать доступ.
   - Закройте все приложения, которые могут использовать проект, и повторите команду.

#### 5. **Глобальная установка пакетов с правами пользователя**
   Если вам не нужны права администратора, можно изменить каталог, используемый для глобальных пакетов `npm`:
   ```bash
   npm config set prefix "%USERPROFILE%\npm-global"
   ```
   Затем добавьте каталог `npm-global/bin` в системную переменную PATH:
   - Откройте свойства системы → Переменные среды.
   - Найдите переменную `PATH` → Добавьте `%USERPROFILE%\npm-global\bin`.

#### 6. **Используйте флаг `--force` или `--unsafe-perm`**
   Иногда помогает установка с флагом:
   ```bash
   npm install --force
   ```
   или
   ```bash
   npm install --unsafe-perm=true
   ```
